v3.0.6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,29 +8,18 @@ cat <<_ZYXW_
 
 Options:
   --help         display this help
-  --debug        create debug exe (CFLAGS='-g -Wall')
-  --arch=[ARCH]  CFLAGS += "-march=ARCH"
-
+  --debug        create debug exe (CFLAGS='-g')
   --prefix=[PREFIX]   install directory
                       [/usr/local]
-  --bindir=[DIR]      install directory of executables
-                      [PREFIX/bin]
-  --datarootdir=[DIR] install directory of system data files
-                      [PREFIX/share]
-  --datadir=[DIR]     install directory of application data files
-                      [DATAROOTDIR]
-  --docdir=[DIR]      install directory of document files
-                      [DATAROOTDIR/doc/PACKAGE]
 
-  --no-check-lib      do not check library
-  --no-pkgconfig      do not use pkg-config command
+  --empty-flags  empty CFLAGS and LDFLAGS by default
 
 Optional flags:
 
 Variables:
   CC       c compiler command
-  CFLAGS   c compiler flags
-  LDFLAGS  linker flags
+  CFLAGS   c compiler flags (-I<include_path> etc)
+  LDFLAGS  linker flags (-L<library_path> etc)
   LIBS     libraries (-l<lib>)
 _ZYXW_
 exit 0
@@ -44,7 +33,7 @@ fc_check_command_err() {
 	if ! type "$1" > /dev/null 2>&1;then
 		echo "[!] '$1' command not found."
 		if test -z "$2";then tmp=$1; else tmp=$2; fi
-		echo "please install '$tmp'"
+		echo "please install: $tmp"
 		exit 1
 	fi
 }
@@ -60,29 +49,10 @@ fc_add_string() {
 	fi
 }
 
-fc_check_sharedlib() {
-	set $1
-	for tmp1;do
-		echo "int main() { return 0; }" > conftest.c
+fc_check_func() {
+	echo "char $1(); int main() { return $1(); }" > conftest.c
 
-		tmp2="-l$tmp1"
-		if $CC $LDFLAGS -o conftest conftest.c $tmp2 > /dev/null 2>&1;then
-			LIBS_ADD=`fc_add_string "$LIBS_ADD" $tmp2`
-			tmp2=yes
-		else
-			tmp2=no
-		fi
-
-		echo "checking lib$tmp1...$tmp2"
-	done
-
-	rm -f conftest.c conftest
-}
-
-fc_check_libfunc() {
-	echo "char $2(); int main() { return $2(); }" > conftest.c
-
-	if $CC $LDFLAGS -o conftest conftest.c -l$1 > /dev/null 2>&1;then
+	if $CC $LDFLAGS $LDFLAGS_ADD -o conftest conftest.c $2 > /dev/null 2>&1;then
 		tmp=0
 	else
 		tmp=1
@@ -93,102 +63,34 @@ fc_check_libfunc() {
 	return $tmp
 }
 
-fc_check_funclink() {
-	tmp_name=$1
-	res=no
-	set $2
-	for tmp;do
-		if fc_check_libfunc $tmp_name $tmp;then
-			res=yes
-			break
-		fi
-	done
-
-	if test $res = yes;then
-		LIBS_ADD=`fc_add_string "$LIBS_ADD" -l$tmp_name`
-	fi
-
-	echo "checking lib$tmp_name...$res"
-}
-
 fc_check_lib() {
 	tmp_name=$1
 	tmp_pkgconf=$2
-	tmp_cflags=$3
-	tmp_libs=$4
-	tmp_includes=$5
-	tmp_incdirs=$6
-	tmp_help=$7
-	tmp_without=$8
+	tmp_help=$3
 
 	echo "checking $tmp_name"
 
-	if test "$tmp_libs";then
-		tmp1=0
-		if test $cf_pkgconfig = yes;then
-			if pkg-config --exists $tmp_pkgconf > /dev/null 2>&1;then tmp1=1; fi
-		fi
-		
-		if test $tmp1 = 1;then
-			tmp1=`pkg-config --cflags $tmp_pkgconf`
-			tmp2=`pkg-config --libs $tmp_pkgconf`
-		else
-			tmp1=$tmp_cflags
-			tmp2=$tmp_libs
-
-			if test -n "$tmp_incdirs";then
-				set $tmp_incdirs
-				for tmp3;do
-					if test -d $tmp3;then
-						tmp1=`fc_add_string "$tmp1" "-I$tmp3"`
-						break
-					fi
-				done
-			fi
-		fi
-
-		CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "$tmp1"`
-		LIBS_ADD=`fc_add_string "$LIBS_ADD" "$tmp2"`
+	if ! pkg-config --exists $tmp_pkgconf > /dev/null 2>&1;then
+		echo "----- Error ----"
+		echo "[!] '$tmp_name' not found"
+		echo "please install: $3"
+		exit 1
 	fi
+	
+	tmp1=`pkg-config --cflags $tmp_pkgconf`
+	tmp2=`pkg-config --libs $tmp_pkgconf`
 
-	# include test
-	if test $cf_check_lib = yes;then
-		touch conftest.c
-
-		set $tmp_includes
-		for tmp1;do
-			echo "#include <$tmp1>" >> conftest.c
-		done
-
-		echo "int main() { return 0; }" >> conftest.c
-
-		$CC $CFLAGS $CFLAGS_ADD -o conftest conftest.c > /dev/null 2>&1
-		tmp1=$?
-		rm -f conftest.c conftest
-
-		if test $tmp1 != 0;then
-			echo "--- Error '$tmp_name' ---"
-			echo "library not found."
-			echo "please install $tmp_help."
-			if test -n "$tmp_without";then
-				echo "--without-$tmp_without : disable support"
-			fi
-			exit 1
-		fi
-	fi
+	CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "$tmp1"`
+	LIBS_ADD=`fc_add_string "$LIBS_ADD" "$tmp2"`
 }
 
-fc_create_makefile() {
+fc_create_buildfile() {
 	cat - <<_ZYXW_ > conftmp
 s|@CC@|$CC|
 s|@CFLAGS@|$CFLAGS|
 s|@LDFLAGS@|$LDFLAGS|
 s|@LIBS@|$LIBS|
 s|@PREFIX@|$cf_prefix|
-s|@BINDIR@|$cf_bindir|
-s|@DATAROOTDIR@|$cf_datarootdir|
-s|@DATADIR@|$cf_datadir|
-s|@DOCDIR@|$cf_docdir|
 s|@PACKAGE_NAME@|$PACKAGE|
 s|@PACKAGE_VERSION@|$PACKAGE_VERSION|
 _ZYXW_
@@ -202,6 +104,8 @@ _ZYXW_
 #----------------
 
 fc_check_command_err sed
+fc_check_command_err ninja "ninja or ninja-build"
+fc_check_command_err pkg-config "pkg-config or pkgconf"
 
 #-------------
 # option
@@ -211,25 +115,16 @@ CFLAGS=
 LDFLAGS=
 LIBS=
 
-CFLAGS_ADD=
-LDFLAGS_ADD=
+CFLAGS_ADD="-I/usr/local/include"
+LDFLAGS_ADD="-L/usr/local/lib"
 LIBS_ADD=
 
 cf_prefix=/usr/local
-cf_bindir=
-cf_datarootdir=
-cf_datadir=
-cf_docdir=
-
-cf_os=unknown
 cf_debug=no
-cf_check_lib=yes
-cf_pkgconfig=no
-
-if fc_check_command pkg-config;then cf_pkgconfig=yes; fi
+cf_empty_flags=no
 
 PACKAGE=azpainter
-PACKAGE_VERSION=3.0.5
+PACKAGE_VERSION=3.0.6
 
 for opt;do
 	case $opt in
@@ -242,26 +137,13 @@ for opt;do
 		fc_put_help ;;
 	--debug)
 		cf_debug=yes ;;
-	--arch=*)
-		CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "-march=$tmp1"` ;;
-	--without-*)
-		tmp1=`expr "x$opt" : 'x--without-\(.*\)'`
-		eval cf_without_$tmp1=yes
-		;;
 	--prefix=*)
 		cf_prefix=$tmp1 ;;
-	--bindir=*)
-		cf_bindir=$tmp1 ;;
-	--datarootdir=*)
-		cf_datarootdir=$tmp1 ;;
-	--datadir=*)
-		cf_datadir=$tmp1 ;;
-	--docdir=*)
-		cf_docdir=$tmp1 ;;
-	--no-check-lib)
-		cf_check_lib=no ;;
-	--no-pkgconfig)
-		cf_pkgconfig=no ;;
+	--empty-flags)
+		cf_empty_flags=yes ;;
+	--without-*)
+		tmp1=`expr "x$opt" : 'x--without-\(.*\)'`
+		eval cf_without_$tmp1=yes ;;
 	*=*)
 		tmp2=`expr "X$opt" : 'X\([^=]*\)=.*'`
 		eval $tmp2=\'$tmp1\' ;;
@@ -275,35 +157,30 @@ done
 
 if test -z "$CFLAGS";then
 	if test "$cf_debug" = yes;then
-		CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "-g -Wall"`
+		CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "-g"`
 	else
-		CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "-O2 -Wall"`
+		CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "-O2"`
 	fi
 fi
 
-# os
-
-tmp1=`uname`
-
-if test "$tmp1" = Linux;then cf_os=linux
-elif test "$tmp1" = Darwin;then
-	cf_os=mac
-	CFLAGS=`fc_add_string "$CFLAGS" "-I/opt/X11/include"`
-	LDFLAGS=`fc_add_string "$LDFLAGS" "-L/opt/X11/lib"`
-	CFLAGS=`fc_add_string "$CFLAGS" "-DMLK_NO_SIMD"`
-elif test "$tmp1" = FreeBSD;then
-	cf_os=freebsd
-	CFLAGS=`fc_add_string "$CFLAGS" "-I/usr/local/include"`
-	LDFLAGS=`fc_add_string "$LDFLAGS" "-L/usr/local/lib"`
+if test "$cf_empty_flags" = yes;then
+	CFLAGS_ADD=""
+	LDFLAGS_ADD=""
 fi
 
-# dir
+cf_os=`uname`
+if test "$cf_os" = Darwin;then
+	cf_os=mac
+else
+	cf_os=n
+fi
 
-if test -z "$cf_bindir";then cf_bindir=$cf_prefix/bin; fi
-if test -z "$cf_datarootdir";then cf_datarootdir=$cf_prefix/share; fi
-if test -z "$cf_datadir";then cf_datadir=$cf_datarootdir; fi
-if test -z "$cf_docdir";then cf_docdir=$cf_datarootdir/doc/$PACKAGE; fi
-
+if test "$cf_os" = mac;then
+	CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "-DMLK_NO_SIMD"`
+	CFLAGS_ADD=`fc_add_string "$CFLAGS_ADD" "-I/opt/X11/include"`
+	LDFLAGS_ADD=`fc_add_string "$LDFLAGS_ADD" "-L/opt/X11/lib"`
+	LIBS_ADD=`fc_add_string "$LIBS_ADD" "-lX11 -lXext -lXcursor -lXi"`
+fi
 
 #-------------
 # compiler
@@ -333,7 +210,7 @@ int main()
 }
 _SRC
 
-if $CC $CFLAGS -o conftest conftest.c > /dev/null 2>&1 && ./conftest;then
+if $CC -o conftest conftest.c > /dev/null 2>&1 && ./conftest;then
 	cf_bigendian=yes
 	echo "endian = big"
 else
@@ -344,20 +221,34 @@ rm -f conftest.c conftest
 
 #------------------
 
-fc_check_sharedlib "iconv"
+echo "checking iconv"
+if fc_check_func iconv_open -liconv || fc_check_func libiconv_open -liconv;then
+	LIBS_ADD=`fc_add_string "$LIBS_ADD" "-liconv"`
+elif ! fc_check_func iconv_open;then
+	echo "[!] 'iconv' not found"
+	echo "please install 'libiconv'"
+	exit 1
+fi
 
-fc_check_funclink rt "clock_gettime"
-fc_check_lib libpng "libpng" "" "-lpng -lz" "png.h" "" "libpng-dev or libpng-devel or libpng or png" ""
-fc_check_lib zlib "zlib" "" "" "zlib.h" "" "zlib1g-dev or zlib-devel or zlib" ""
-fc_check_lib libjpeg "libjpeg" "" "-ljpeg" "stdio.h jpeglib.h" "" "libjpeg-dev or libjpeg-devel or libjpeg-turbo or jpeg-turbo" ""
-fc_check_lib libtiff "libtiff-4" "" "-ltiff" "tiff.h" "" "libtiff-dev or libtiff-devel or libtiff or tiff" ""
-fc_check_lib libwebp "libwebp" "" "-lwebp" "webp/decode.h" "" "libwebp-dev or libwebp-devel or libwebp or webp" ""
-fc_check_lib x11 "x11" "" "-lX11" "X11/Xlib.h" "" "libx11-dev or libX11-devel or libx11" ""
-fc_check_lib xext "xext" "" "-lXext" "X11/Xlib.h X11/extensions/XShm.h" "" "libxext-dev or libXext-devel or libxext" ""
-fc_check_lib xcursor "xcursor" "" "-lXcursor" "X11/Xlib.h X11/Xcursor/Xcursor.h" "" "libxcursor-dev or libXcursor-devel or libxcursor" ""
-fc_check_lib xinput "xi" "" "-lXi" "X11/Xlib.h X11/extensions/XInput2.h" "" "libxi-dev or libXi-devel or libxi" ""
-fc_check_lib fontconfig "fontconfig" "" "-lfontconfig -lfreetype" "fontconfig/fontconfig.h" "/usr/include/freetype2 /usr/local/include/freetype2 /opt/X11/include/freetype2" "libfontconfig1-dev or libfontconfig-devel or fontconfig" ""
-fc_check_lib freetype2 "freetype2" "" "" "ft2build.h" "" "libfreetype6-dev or libfreetype6-devel or freetype2" ""
+if test $cf_os != mac;then
+	fc_check_lib x11 x11 "libx11-dev or libX11-devel or libx11"
+fi
+if test $cf_os != mac;then
+	fc_check_lib xext xext "libxext-dev or libXext-devel or libxext"
+fi
+if test $cf_os != mac;then
+	fc_check_lib xcursor xcursor "libxcursor-dev or libXcursor-devel or libxcursor"
+fi
+if test $cf_os != mac;then
+	fc_check_lib xinput xi "libxi-dev or libXi-devel or libxi"
+fi
+fc_check_lib png libpng "libpng-dev or libpng-devel or libpng or png"
+fc_check_lib zlib zlib "zlib1g-dev or zlib-devel or zlib"
+fc_check_lib tiff libtiff-4 "libtiff-dev or libtiff-devel or libtiff or tiff"
+fc_check_lib jpeg libjpeg "libjpeg-dev or libjpeg-devel or libjpeg-turbo or jpeg-turbo"
+fc_check_lib webp libwebp "libwebp-dev or libwebp-devel or libwebp or webp"
+fc_check_lib freetype2 freetype2 "libfreetype6-dev or libfreetype6-devel or freetype2"
+fc_check_lib fontconfig fontconfig "libfontconfig1-dev or libfontconfig-devel or fontconfig"
 
 if test ! -d build;then mkdir build; fi
 
@@ -369,7 +260,7 @@ touch conftmp
 if test $cf_bigendian = yes;then
 	echo "s|\\#undef MLK_BIG_ENDIAN|\\#define MLK_BIG_ENDIAN|" >> conftmp
 fi
-if ! fc_check_libfunc freetype FT_Done_MM_Var;then
+if ! fc_check_func FT_Done_MM_Var "-lfreetype";then
 	echo "s|\\#undef MLK_NO_FREETYPE_VARIABLE|\\#define MLK_NO_FREETYPE_VARIABLE|" >> conftmp
 fi
 
@@ -388,8 +279,8 @@ CFLAGS=`fc_add_string "$CFLAGS" "$CFLAGS_ADD"`
 LDFLAGS=`fc_add_string "$LDFLAGS" "$LDFLAGS_ADD"`
 LIBS=`fc_add_string "$LIBS" "$LIBS_ADD"`
 
-fc_create_makefile build.ninja.in build/build.ninja
-fc_create_makefile install.sh.in build/install.sh
+fc_create_buildfile build.ninja.in build/build.ninja
+fc_create_buildfile install.sh.in build/install.sh
 
 cat <<_ZYXW_
 ---------------
@@ -405,4 +296,3 @@ please run...
 ---------------
 _ZYXW_
 
-fc_check_command_err ninja "ninja or ninja-build"
